### ISSUE TITLE
能不能教我Stream模式下的接收文件

### ISSUE THREAD

**Issue by windy664** [chzealot/dingtalk-stream-example-python#1]
能不能教我Stream模式下的接收文件
就是检测到文件上传这个
恳请您教下如何操作！

**Comment by chzealot** [comment]
可以参考这篇文档：
[Stream Mode 常见问题](https://open-dingtalk.github.io/developerpedia/docs/learn/stream/faq#%E6%9C%BA%E5%99%A8%E4%BA%BA%E8%83%BD%E6%8E%A5%E6%94%B6%E5%9B%BE%E7%89%87%E5%90%97)
